name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps: 
    - uses: actions/checkout@v4
    
    # Pythonの環境をセットアップ
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    # 必要なパッケージをインストール
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest numpy scipy

    - name: Build
      run: make

    - name: Test
      run: make tests

    # テスト結果をアップロードする
    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: test_results
        path: tests/*/*.xml

    # テスト結果をダウンロードする
    - name: Download results
      uses: actions/download-artifact@v4
      with:
        name: test_results
        path: artifacts

    # テスト結果をGitHub上で表示する
    - name: display results
      uses: GitHubSecurityLab/actions-permissions/monitor@v1
      with:
        config: ${{ vars.PERMISSIONS_CONFIG }}   
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: artifacts/**/*.xml
