name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # Pythonの環境をセットアップ
    - name: Set up Python
      uses: actions/setup-python@v5

    # pytestをインストール
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Build
      run: make
